Sl 115 회원은 스터디를 생성할 수 있다
dev-Dive/StudyLog pull request #23
Opened 2023-10-08 11:22 UTC by kang-seongbeom

- [X] 🔀 PR 제목의 형식을 잘 작성했나요? e.g. `PR을 등록한다.` 
- [X] 💯 테스트는 잘 통과했나요?
- [X] 🧹 불필요한 코드는 제거했나요?
- [X] 💭 이슈는 등록했나요?
- [X] 🏷️ 라벨은 등록했나요?
- [X] 💻 git rebase를 사용했나요?

## 작업 내용
스터디 생성

## 스크린샷 (선택)

## 참고사항

close #{이슈 번호}
Sl 115

2023-10-10 05:23 UTC, acisliver requested changes

2023-10-10 05:23 UTC, acisliver commented on backend/src/main/java/com/devdive/backend/study/adapter/in/web/StudyController.java
> +    @PostMapping("v1/study/create")
/api가 빠졌고 명세랑 api가 다르네요

2023-10-10 05:23 UTC, acisliver commented on backend/src/main/java/com/devdive/backend/study/adapter/out/persistence/MappingTableStudyMemberJpaEntity.java
> +@Entity(name = "study_member")
엔티티보다는 테이블 어노테이션을 사용하는게 좋을 것 같고 s가 빠졌네요

2023-10-10 05:23 UTC, acisliver commented on backend/src/main/java/com/devdive/backend/study/adapter/out/persistence/MappingTableStudyMemberJpaEntity.java
> +public class MappingTableStudyMemberJpaEntity {
굳이 MappingTable이라고 적지 않아도 될 것 같습니다

2023-10-10 05:23 UTC, acisliver commented on backend/src/main/java/com/devdive/backend/study/adapter/out/persistence/MemberStudyJpaEntity.java
> +@Table(name = "member")
```suggestion
@Table(name = "members")
```

2023-10-10 05:23 UTC, acisliver commented on backend/src/main/java/com/devdive/backend/study/adapter/out/persistence/StudyJpaEntity.java
> +@Entity(name = "study")
엔티티 대신 테이블. 그리고 s 빠짐

2023-10-10 05:23 UTC, acisliver commented on backend/src/main/java/com/devdive/backend/study/application/dto/StudyCreateDto.java
DTO를 서로 다른 클래스가 공유해서 사용 중입니다. 그래서 DTO는 내부 클래스가 좋을 것 같습니다.

2023-10-13 07:35 UTC, rhwlgns4386 commented on backend/src/main/java/com/devdive/backend/study/adapter/out/persistence/StudyPersistenceAdapter.java
> +        mappingTable.setMember(member);
현재 MappingTableStudyMemberJpaEntity가 domain class가 아닌 data만 들어가는 VO와 다르지 않은 것 같아서 개인적으로 setter을 죽이고 contructor로 입력받는게 어떨까요?

2023-10-15 11:43 UTC, acisliver approved these changes

2023-10-15 11:43 UTC, merged